language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libepoxy-dev
            - libcairo2-dev
script:
  - mkdir build
  - cd build
  - CC="$(which gcc-6)" CXX="$(which g++-6)" cmake .. -DPYTHON_EXECUTABLE="$(which python3)"
  - make
  - ./drnsf :internal-test
